#!/usr/bin/env python3
"""Generate the runtime-safe XZIEL Mystery Box allow-list.

The identity pool is intentionally broader than the playable pool. A weapon
enters the generated .mb2 only after every presentation/gameplay lane required
for a non-broken Box reward is complete.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "assets/weapons/xziel_weapon_catalog_v1.json"
IDENTITY_POOL = ROOT / "assets/weapons/xziel_mystery_box_pool_v1.json"
REGISTRY = ROOT / "assets/weapons/xziel_weapon_id_registry_v1.json"
CONTRACT = ROOT / "assets/nacht_reference/bo3_nacht_completion_contract_v1.json"
MANIFEST = ROOT / "assets/weapons/xziel_mystery_box_runtime_pool_v1.json"
MB2_OUT = Path(
    os.environ.get(
        "XZIEL_MYSTERY_BOX_MB2_OUT",
        ROOT / "build/nacht_harness/xziel_nacht_bo3.mb2",
    )
)

REQUIRED_LANES = (
    "source_stats",
    "behavior_spec",
    "native_gameplay",
    "model",
    "audio",
    "recoil",
    "spread",
    "animations",
    "penetration",
    "android_exposure",
    "regression_test",
)
COMPLETE_STATES = {"ready", "not_applicable"}


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    catalog = load(CATALOG)
    identity_pool = load(IDENTITY_POOL)
    registry = load(REGISTRY)
    contract = load(CONTRACT)

    catalog_by_id = {w["weaponId"]: w for w in catalog["weapons"]}
    registry_by_id = {w["weaponId"]: w for w in registry["entries"]}
    tracked = contract["weapons"]

    candidates = identity_pool["weaponIds"]
    active = []
    blocked = []

    for wid in candidates:
        if wid not in catalog_by_id:
            raise SystemExit(f"runtime pool candidate missing from catalog: {wid}")
        if wid not in registry_by_id:
            raise SystemExit(f"runtime pool candidate missing from ID registry: {wid}")
        if wid not in tracked:
            raise SystemExit(f"runtime pool candidate missing from completion contract: {wid}")

        cat = catalog_by_id[wid]
        row = tracked[wid]
        lanes = row["lanes"]

        reasons = []
        if cat.get("nativeBindingStatus") != "ready":
            reasons.append(f"nativeBindingStatus={cat.get('nativeBindingStatus')}")

        for lane in REQUIRED_LANES:
            state = lanes.get(lane)
            if state not in COMPLETE_STATES:
                reasons.append(f"{lane}={state}")

        if reasons:
            blocked.append(
                {
                    "weaponId": wid,
                    "displayName": cat["displayName"],
                    "mboxToken": registry_by_id[wid]["mboxToken"],
                    "reasons": reasons,
                }
            )
        else:
            active.append(
                {
                    "weaponId": wid,
                    "displayName": cat["displayName"],
                    "mboxToken": registry_by_id[wid]["mboxToken"],
                    "quakecId": registry_by_id[wid]["quakecId"],
                }
            )

    manifest = {
        "schemaVersion": 1,
        "poolId": "xziel_mystery_box_runtime_ready_v1",
        "policy": "zero_broken_rewards",
        "candidatePool": str(IDENTITY_POOL.relative_to(ROOT)),
        "completionContract": str(CONTRACT.relative_to(ROOT)),
        "weaponIdRegistry": str(REGISTRY.relative_to(ROOT)),
        "requiredLanes": list(REQUIRED_LANES),
        "candidateCount": len(candidates),
        "activeCount": len(active),
        "blockedCount": len(blocked),
        "active": active,
        "blocked": blocked,
        "notes": [
            "Identity availability is not equivalent to runtime readiness.",
            "Only active entries are emitted to the NZ:P .mb2 allow-list.",
            "An empty active list is valid during development; the patched box must refuse purchase without charging the player.",
        ],
    }

    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    MB2_OUT.parent.mkdir(parents=True, exist_ok=True)
    mb2_lines = [
        "nzp_mbox2",
        "allow:",
        "# Generated by XZIEL readiness gate. Do not hand-edit.",
    ]
    mb2_lines.extend(row["mboxToken"] for row in active)
    MB2_OUT.write_text("\n".join(mb2_lines) + "\n", encoding="utf-8")

    print(
        "XZIEL_MYSTERY_BOX_RUNTIME_POOL_OK "
        f"candidates={len(candidates)} active={len(active)} blocked={len(blocked)} "
        f"mb2={MB2_OUT}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
